// -*- coding: utf-8 -*-
// База данных всех рыб в игре (120 видов)
// Спрайты: fish_001.png - fish_120.png (пока используются эмодзи)

const FISH_DATABASE = [
  {
    id: 1,
    zoneId: 1,
    name: "Плотва",
    role: "peace",
    rarity: "Common",
    weightMin: 0.03,
    weightMax: 0.12,
    power: 5,
    biteStyle: "Тык-тык (мелкие касания)",
    timeOfDay: "День",
    preferredBaitId: 1,
    altBaitId: 15, // Мотыль
    minGearTier: 1,
    tierPowerCap: 10,
    sellPrice: 7,
    xp: 1,
    sprite: "fish_001.png",
    emoji: "🐟",
    description: "Осторожная мирная рыба, предпочитающая стоячую воду. Клюёт мелкими касаниями, особенно активна в дневное время.",
    description: "Осторожная мирная рыба, предпочитающая стоячую воду. Клюёт мелкими касаниями, особенно активна в дневное время."
  },
  {
    id: 2,
    zoneId: 1,
    name: "Карась",
    role: "peace",
    rarity: "Common",
    weightMin: 0.06,
    weightMax: 0.42,
    power: 6,
    biteStyle: "Плавное притапливание",
    timeOfDay: "Вечер",
    preferredBaitId: 1,
    altBaitId: 15, // Мотыль
    minGearTier: 1,
    tierPowerCap: 10,
    sellPrice: 22,
    xp: 6,
    sprite: "fish_002.png",
    emoji: "🐠",
    description: "Донная мирная рыба, обитающая в прудах и озёрах. Клюёт плавно, притапливая поплавок, наиболее активна в вечерние часы.",
    description: "Донная мирная рыба, обитающая в прудах и озёрах. Клюёт плавно, притапливая поплавок, наиболее активна в вечерние часы."
  },
  {
    id: 3,
    zoneId: 1,
    name: "Краснопёрка",
    role: "peace",
    rarity: "Uncommon",
    weightMin: 0.04,
    weightMax: 0.19,
    power: 7,
    biteStyle: "Фальстарт (взял/бросил)",
    timeOfDay: "День",
    preferredBaitId: 1,
    altBaitId: 15, // Мотыль
    minGearTier: 1,
    tierPowerCap: 10,
    sellPrice: 14,
    xp: 4,
    sprite: "fish_003.png",
    emoji: "🐟",
    description: "Стайная рыба с осторожным поведением. Часто берёт наживку и бросает её, требует терпения при подсечке.",
    description: "Стайная рыба с осторожным поведением. Часто берёт наживку и бросает её, требует терпения при подсечке."
  },
  {
    id: 4,
    zoneId: 1,
    name: "Окунь",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 0.07,
    weightMax: 0.32,
    power: 8,
    biteStyle: "Серия ударов (дробь)",
    timeOfDay: "День",
    preferredBaitId: 2,
    altBaitId: 5,
    minGearTier: 1,
    tierPowerCap: 10,
    sellPrice: 23,
    xp: 6,
    sprite: "fish_004.png",
    emoji: "🐡",
    description: "Активный хищник, атакующий наживку серией коротких ударов. Обитает в прибрежных зонах, охотится днём.",
    description: "Активный хищник, атакующий наживку серией коротких ударов. Обитает в прибрежных зонах, охотится днём."
  },
  {
    id: 5,
    zoneId: 1,
    name: "Густера",
    role: "peace",
    rarity: "Common",
    weightMin: 0.04,
    weightMax: 0.21,
    power: 7,
    biteStyle: "Плавное притапливание",
    timeOfDay: "Вечер",
    preferredBaitId: 5,
    altBaitId: 17, // Манка
    minGearTier: 1,
    tierPowerCap: 10,
    sellPrice: 11,
    xp: 3,
    sprite: "fish_005.png",
    emoji: "🐟",
    description: "Мирная стайная рыба, предпочитающая тихие заводи. Клюёт плавно, особенно активна в вечернее время.",
    description: "Мирная стайная рыба, предпочитающая тихие заводи. Клюёт плавно, особенно активна в вечернее время."
  },
  {
    id: 6,
    zoneId: 1,
    name: "Карась трофейный",
    role: "peace",
    rarity: "Rare",
    weightMin: 0.39,
    weightMax: 0.84,
    power: 10,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Ночь",
    preferredBaitId: 3,
    altBaitId: 16, // Перловка
    minGearTier: 1,
    tierPowerCap: 10,
    sellPrice: 150,
    xp: 37,
    sprite: "fish_006.png",
    emoji: "🐠",
    description: "Крупный трофейный карась, выходящий на кормёжку ночью. Сопротивляется мощными рывками при вываживании.",
    description: "Крупный трофейный карась, выходящий на кормёжку ночью. Сопротивляется мощными рывками при вываживании."
  },
  {
    id: 7,
    zoneId: 2,
    name: "Линь",
    role: "peace",
    rarity: "Common",
    weightMin: 0.12,
    weightMax: 0.77,
    power: 10,
    biteStyle: "Плавное притапливание",
    timeOfDay: "Утро/Вечер",
    preferredBaitId: 2,
    altBaitId: 15, // Мотыль
    minGearTier: 2,
    tierPowerCap: 15,
    sellPrice: 40,
    xp: 10,
    sprite: "fish_007.png",
    emoji: "🐟",
    description: "Донная мирная рыба, обитающая в заросших водоёмах. Клюёт плавно, наиболее активна утром и вечером.",
    description: "Донная мирная рыба, обитающая в заросших водоёмах. Клюёт плавно, наиболее активна утром и вечером."
  },
  {
    id: 8,
    zoneId: 2,
    name: "Лещ",
    role: "peace",
    rarity: "Common",
    weightMin: 0.25,
    weightMax: 1.23,
    power: 12,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Вечер",
    preferredBaitId: 3,
    altBaitId: 19, // Пшеница
    minGearTier: 2,
    tierPowerCap: 15,
    sellPrice: 66,
    xp: 16,
    sprite: "fish_008.png",
    emoji: "🐠",
    description: "Крупная донная рыба, клюёт как зацеп за дно. Предпочитает вечернее время, сопротивляется тяжестью своего тела.",
    description: "Крупная донная рыба, клюёт как зацеп за дно. Предпочитает вечернее время, сопротивляется тяжестью своего тела."
  },
  {
    id: 9,
    zoneId: 2,
    name: "Карась серебряный",
    role: "peace",
    rarity: "Uncommon",
    weightMin: 0.11,
    weightMax: 0.63,
    power: 11,
    biteStyle: "Фальстарт (взял/бросил)",
    timeOfDay: "Вечер",
    preferredBaitId: 1,
    altBaitId: 15, // Мотыль
    minGearTier: 2,
    tierPowerCap: 15,
    sellPrice: 45,
    xp: 11,
    sprite: "fish_009.png",
    emoji: "🐟",
    description: "Осторожная мирная рыба с серебристой чешуёй. Часто пробует наживку перед заглатыванием, активна вечером.",
    description: "Осторожная мирная рыба с серебристой чешуёй. Часто пробует наживку перед заглатыванием, активна вечером."
  },
  {
    id: 10,
    zoneId: 2,
    name: "Щука (мелкая)",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 0.28,
    weightMax: 1.23,
    power: 15,
    biteStyle: "Резкий уход в сторону",
    timeOfDay: "День",
    preferredBaitId: 7,
    altBaitId: 8,
    minGearTier: 2,
    tierPowerCap: 15,
    sellPrice: 92,
    xp: 22,
    sprite: "fish_010.png",
    emoji: "🦈",
    description: "Молодая щука, агрессивный хищник. Атакует резким уходом в сторону, охотится в светлое время суток.",
    description: "Молодая щука, агрессивный хищник. Атакует резким уходом в сторону, охотится в светлое время суток."
  },
  {
    id: 11,
    zoneId: 2,
    name: "Плотва крупная",
    role: "peace",
    rarity: "Uncommon",
    weightMin: 0.11,
    weightMax: 0.28,
    power: 12,
    biteStyle: "Тык-тык (мелкие касания)",
    timeOfDay: "День",
    preferredBaitId: 5,
    altBaitId: 15, // Мотыль
    minGearTier: 2,
    tierPowerCap: 15,
    sellPrice: 23,
    xp: 6,
    sprite: "fish_011.png",
    emoji: "🐟",
    description: "Крупная плотва, обитающая в реках и озёрах. Клюёт мелкими касаниями, активна в дневное время.",
    description: "Крупная плотва, обитающая в реках и озёрах. Клюёт мелкими касаниями, активна в дневное время."
  },
  {
    id: 12,
    zoneId: 2,
    name: "Угорь",
    role: "bottom",
    rarity: "Rare",
    weightMin: 0.25,
    weightMax: 1.05,
    power: 16,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Ночь",
    preferredBaitId: 2,
    altBaitId: 11,
    minGearTier: 3,
    tierPowerCap: 20,
    sellPrice: 111,
    xp: 27,
    sprite: "fish_012.png",
    emoji: "🐍",
    description: "Донный хищник, ведущий ночной образ жизни. Клюёт как зацеп, сопротивляется извивающимися движениями.",
    description: "Донный хищник, ведущий ночной образ жизни. Клюёт как зацеп, сопротивляется извивающимися движениями."
  },
  {
    id: 13,
    zoneId: 3,
    name: "Голавль",
    role: "peace",
    rarity: "Common",
    weightMin: 0.14,
    weightMax: 0.7,
    power: 15,
    biteStyle: "Фальстарт (взял/бросил)",
    timeOfDay: "День",
    preferredBaitId: 2,
    altBaitId: 21, // Саранча
    minGearTier: 3,
    tierPowerCap: 20,
    sellPrice: 38,
    xp: 9,
    sprite: "fish_013.png",
    emoji: "🐟",
    description: "Речная мирная рыба, обитающая на течении. Осторожно пробует наживку, активна в дневное время."
  },
  {
    id: 14,
    zoneId: 3,
    name: "Язь",
    role: "peace",
    rarity: "Uncommon",
    weightMin: 0.19,
    weightMax: 0.98,
    power: 16,
    biteStyle: "Плавное притапливание",
    timeOfDay: "День",
    preferredBaitId: 5,
    altBaitId: 20, // Кузнечик
    minGearTier: 3,
    tierPowerCap: 20,
    sellPrice: 71,
    xp: 18,
    sprite: "fish_014.png",
    emoji: "🐠",
    description: "Крупная мирная рыба, предпочитающая реки с умеренным течением. Клюёт плавно, активна днём."
  },
  {
    id: 15,
    zoneId: 3,
    name: "Подуст",
    role: "peace",
    rarity: "Common",
    weightMin: 0.12,
    weightMax: 0.42,
    power: 14,
    biteStyle: "Тык-тык (мелкие касания)",
    timeOfDay: "День",
    preferredBaitId: 5,
    altBaitId: 17, // Манка
    minGearTier: 3,
    tierPowerCap: 20,
    sellPrice: 25,
    xp: 6,
    sprite: "fish_015.png",
    emoji: "🐟",
    description: "Речная рыба, держащаяся у дна на течении. Клюёт мелкими касаниями, активна в светлое время."
  },
  {
    id: 16,
    zoneId: 3,
    name: "Жерех",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 0.32,
    weightMax: 1.12,
    power: 18,
    biteStyle: "Резкий уход в сторону",
    timeOfDay: "День",
    preferredBaitId: 7,
    altBaitId: 20, // Кузнечик
    minGearTier: 3,
    tierPowerCap: 20,
    sellPrice: 88,
    xp: 21,
    sprite: "fish_016.png",
    emoji: "🐡",
    description: "Быстрый речной хищник, атакующий добычу резкими рывками. Охотится в дневное время на течении."
  },
  {
    id: 17,
    zoneId: 3,
    name: "Судак (молодь)",
    role: "pred",
    rarity: "Rare",
    weightMin: 0.42,
    weightMax: 1.47,
    power: 20,
    biteStyle: "Молниеносная атака",
    timeOfDay: "Вечер/Ночь",
    preferredBaitId: 7,
    altBaitId: 11,
    minGearTier: 3,
    tierPowerCap: 20,
    sellPrice: 162,
    xp: 39,
    sprite: "fish_017.png",
    emoji: "🦈",
    description: "Молодой судак, ночной хищник. Атакует молниеносно, сопротивляется резкими рывками при вываживании."
  },
  {
    id: 18,
    zoneId: 3,
    name: "Сомик",
    role: "bottom",
    rarity: "Rare",
    weightMin: 0.53,
    weightMax: 2.28,
    power: 21,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Ночь",
    preferredBaitId: 11,
    altBaitId: 2,
    minGearTier: 4,
    tierPowerCap: 25,
    sellPrice: 342,
    xp: 84,
    sprite: "fish_018.png",
    emoji: "🐈",
    description: "Донный хищник, обитающий в глубоких ямах. Клюёт как зацеп, активен ночью, сопротивляется мощно."
  },
  {
    id: 19,
    zoneId: 4,
    name: "Форель ручьевая",
    role: "pred",
    rarity: "Common",
    weightMin: 0.17,
    weightMax: 0.88,
    power: 18,
    biteStyle: "Серия ударов (дробь)",
    timeOfDay: "День",
    preferredBaitId: 6,
    altBaitId: 21, // Саранча
    minGearTier: 4,
    tierPowerCap: 25,
    sellPrice: 30,
    xp: 7,
    sprite: "fish_019.png",
    emoji: "🐟",
    description: "Хищная рыба горных рек, атакующая наживку серией ударов. Предпочитает чистую холодную воду, активна днём."
  },
  {
    id: 20,
    zoneId: 4,
    name: "Хариус",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 0.14,
    weightMax: 0.61,
    power: 17,
    biteStyle: "Тык-тык (мелкие касания)",
    timeOfDay: "День",
    preferredBaitId: 6,
    altBaitId: 20, // Кузнечик
    minGearTier: 4,
    tierPowerCap: 25,
    sellPrice: 29,
    xp: 7,
    sprite: "fish_020.png",
    emoji: "🐠",
    description: "Рыба быстрых горных рек, клюёт осторожными касаниями. Обитает в холодной воде, активна в дневное время."
  },
  {
    id: 21,
    zoneId: 4,
    name: "Гольц",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 0.19,
    weightMax: 1.21,
    power: 19,
    biteStyle: "Серия ударов (дробь)",
    timeOfDay: "День",
    preferredBaitId: 6,
    altBaitId: 2,
    minGearTier: 4,
    tierPowerCap: 25,
    sellPrice: 54,
    xp: 13,
    sprite: "fish_021.png",
    emoji: "🐟",
    description: "Хищник холодных рек, атакующий добычу серией ударов. Предпочитает чистую воду, охотится днём."
  },
  {
    id: 22,
    zoneId: 4,
    name: "Форель радужная",
    role: "pred",
    rarity: "Rare",
    weightMin: 0.66,
    weightMax: 1.93,
    power: 22,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Утро/Вечер",
    preferredBaitId: 6,
    altBaitId: 21, // Саранча
    minGearTier: 4,
    tierPowerCap: 25,
    sellPrice: 141,
    xp: 34,
    sprite: "fish_022.png",
    emoji: "🌈",
    description: "Трофейная форель, сопротивляющаяся мощными рывками. Наиболее активна утром и вечером в холодной воде."
  },
  {
    id: 23,
    zoneId: 4,
    name: "Таймень (молодь)",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 1.65,
    weightMax: 3.85,
    power: 25,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Вечер",
    preferredBaitId: 7,
    altBaitId: 11,
    minGearTier: 4,
    tierPowerCap: 25,
    sellPrice: 456,
    xp: 112,
    sprite: "fish_023.png",
    emoji: "🦈",
    description: "Молодой таймень, крупный хищник сибирских рек. Атакует мощным рывком, активен в вечернее время."
  },
  {
    id: 24,
    zoneId: 4,
    name: "Ленок",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 0.33,
    weightMax: 1.38,
    power: 21,
    biteStyle: "Серия ударов (дробь)",
    timeOfDay: "День",
    preferredBaitId: 6,
    altBaitId: 2,
    minGearTier: 4,
    tierPowerCap: 25,
    sellPrice: 66,
    xp: 16,
    sprite: "fish_024.png",
    emoji: "🐟",
    description: "Хищник холодных рек, атакующий наживку серией ударов. Обитает в быстрой воде, охотится днём."
  },
  {
    id: 25,
    zoneId: 5,
    name: "Карп зеркальный",
    role: "peace",
    rarity: "Common",
    weightMin: 0.66,
    weightMax: 3.58,
    power: 31,
    biteStyle: "Плавное притапливание",
    timeOfDay: "Утро/Вечер",
    preferredBaitId: 4,
    altBaitId: 18, // Горох
    minGearTier: 6,
    tierPowerCap: 35,
    sellPrice: 121,
    xp: 29,
    sprite: "fish_025.png",
    emoji: "🐠",
    description: "Крупная мирная рыба, обитающая в прудах и озёрах. Клюёт плавно, наиболее активна утром и вечером."
  },
  {
    id: 26,
    zoneId: 5,
    name: "Сазан",
    role: "peace",
    rarity: "Uncommon",
    weightMin: 0.99,
    weightMax: 5.5,
    power: 33,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Вечер",
    preferredBaitId: 4,
    altBaitId: 16, // Перловка
    minGearTier: 6,
    tierPowerCap: 35,
    sellPrice: 251,
    xp: 62,
    sprite: "fish_026.png",
    emoji: "🐟",
    description: "Дикий карп, сопротивляющийся мощными рывками. Осторожная рыба, активная в вечернее время."
  },
  {
    id: 27,
    zoneId: 5,
    name: "Амур белый",
    role: "peace",
    rarity: "Rare",
    weightMin: 1.38,
    weightMax: 7.15,
    power: 34,
    biteStyle: "Фальстарт (взял/бросил)",
    timeOfDay: "День",
    preferredBaitId: 4,
    altBaitId: 18, // Горох
    minGearTier: 6,
    tierPowerCap: 35,
    sellPrice: 464,
    xp: 113,
    sprite: "fish_027.png",
    emoji: "🐠",
    description: "Крупная травоядная рыба, осторожно пробующая наживку. Сопротивляется мощно, активна в дневное время."
  },
  {
    id: 28,
    zoneId: 5,
    name: "Щука",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 1.1,
    weightMax: 4.95,
    power: 34,
    biteStyle: "Резкий уход в сторону",
    timeOfDay: "День",
    preferredBaitId: 7,
    altBaitId: 8,
    minGearTier: 6,
    tierPowerCap: 35,
    sellPrice: 234,
    xp: 57,
    sprite: "fish_028.png",
    emoji: "🦈",
    description: "Крупный речной хищник, атакующий резкими боковыми рывками. Охотится в светлое время суток."
  },
  {
    id: 29,
    zoneId: 5,
    name: "Лещ трофейный",
    role: "peace",
    rarity: "Rare",
    weightMin: 1.38,
    weightMax: 3.03,
    power: 33,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Вечер",
    preferredBaitId: 3,
    altBaitId: 18, // Горох
    minGearTier: 6,
    tierPowerCap: 35,
    sellPrice: 239,
    xp: 59,
    sprite: "fish_029.png",
    emoji: "🐟",
    description: "Трофейный лещ, клюющий как зацеп за дно. Предпочитает вечернее время, сопротивляется тяжестью тела."
  },
  {
    id: 30,
    zoneId: 5,
    name: "Сом",
    role: "bottom",
    rarity: "Uncommon",
    weightMin: 3.3,
    weightMax: 12.1,
    power: 36,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Ночь",
    preferredBaitId: 11,
    altBaitId: 8,
    minGearTier: 7,
    tierPowerCap: 40,
    sellPrice: 1279,
    xp: 313,
    sprite: "fish_030.png",
    emoji: "🐈",
    description: "Гигантский донный хищник, клюющий как зацеп. Ночной охотник, сопротивляется огромной силой."
  }
];

// Рыбы 31-60
FISH_DATABASE.push(
  {
    id: 31,
    zoneId: 6,
    name: "Налим",
    role: "bottom",
    rarity: "Common",
    weightMin: 0.66,
    weightMax: 3.03,
    power: 36,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Ночь",
    preferredBaitId: 2,
    altBaitId: 11,
    minGearTier: 7,
    tierPowerCap: 40,
    sellPrice: 106,
    xp: 26,
    sprite: "fish_031.png",
    emoji: "🐟",
    description: "Единственный представитель тресковых в Байкале. Донный хищник, активный в холодной воде ночью."
  },
  {
    id: 32,
    zoneId: 6,
    name: "Сиг",
    role: "peace",
    rarity: "Uncommon",
    weightMin: 0.44,
    weightMax: 1.43,
    power: 34,
    biteStyle: "Тык-тык (мелкие касания)",
    timeOfDay: "День",
    preferredBaitId: 5,
    altBaitId: 6,
    minGearTier: 6,
    tierPowerCap: 35,
    sellPrice: 72,
    xp: 18,
    sprite: "fish_032.png",
    emoji: "🐠",
    description: "Байкальский сиг - эндемик озера. Ценная промысловая рыба, клюёт осторожными касаниями в толще воды."
  },
  {
    id: 33,
    zoneId: 6,
    name: "Кумжа",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 0.88,
    weightMax: 3.58,
    power: 37,
    biteStyle: "Серия ударов (дробь)",
    timeOfDay: "День",
    preferredBaitId: 6,
    altBaitId: 11,
    minGearTier: 7,
    tierPowerCap: 40,
    sellPrice: 172,
    xp: 42,
    sprite: "fish_033.png",
    emoji: "🐟",
    description: "Байкальская форель, хищник чистых вод. Атакует добычу серией ударов, предпочитает прибрежные зоны."
  },
  {
    id: 34,
    zoneId: 6,
    name: "Лосось",
    role: "pred",
    rarity: "Rare",
    weightMin: 1.65,
    weightMax: 6.6,
    power: 39,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Утро",
    preferredBaitId: 7,
    altBaitId: 11,
    minGearTier: 7,
    tierPowerCap: 40,
    sellPrice: 449,
    xp: 110,
    sprite: "fish_034.png",
    emoji: "🐟",
    description: "Проходной лосось в притоках Байкала. Мощный хищник, заходящий в озеро на нагул, активен утром."
  },
  {
    id: 35,
    zoneId: 6,
    name: "Таймень",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 4.4,
    weightMax: 13.75,
    power: 41,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Вечер",
    preferredBaitId: 7,
    altBaitId: 11,
    minGearTier: 8,
    tierPowerCap: 45,
    sellPrice: 1507,
    xp: 368,
    sprite: "fish_035.png",
    emoji: "🦈",
    description: "Байкальский таймень - король сибирских рек. Гигантский хищник, заходящий в озеро из притоков."
  },
  {
    id: 36,
    zoneId: 6,
    name: "Хариус крупный",
    role: "pred",
    rarity: "Rare",
    weightMin: 0.55,
    weightMax: 1.38,
    power: 36,
    biteStyle: "Серия ударов (дробь)",
    timeOfDay: "День",
    preferredBaitId: 6,
    altBaitId: 21, // Саранча
    minGearTier: 7,
    tierPowerCap: 40,
    sellPrice: 105,
    xp: 26,
    sprite: "fish_036.png",
    emoji: "🐠",
    description: "Байкальский хариус - красивейшая рыба озера. Обитает в чистейших водах, атакует серией ударов."
  },
  {
    id: 37,
    zoneId: 7,
    name: "Кефаль",
    role: "peace",
    rarity: "Common",
    weightMin: 0.7,
    weightMax: 3.2,
    power: 37,
    biteStyle: "Плавное притапливание",
    timeOfDay: "День",
    preferredBaitId: 9,
    altBaitId: 1,
    minGearTier: 7,
    tierPowerCap: 40,
    sellPrice: 88,
    xp: 21,
    sprite: "fish_037.png",
    emoji: "🐟",
    description: "Прибрежная мирная рыба, клюющая плавно. Держится стаями, активна в дневное время."
  },
  {
    id: 38,
    zoneId: 7,
    name: "Судак",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 2.5,
    weightMax: 7.5,
    power: 40,
    biteStyle: "Молниеносная атака",
    timeOfDay: "Вечер/Ночь",
    preferredBaitId: 7,
    altBaitId: 11,
    minGearTier: 7,
    tierPowerCap: 40,
    sellPrice: 213,
    xp: 52,
    sprite: "fish_038.png",
    emoji: "🦈",
    description: "Крупный ночной хищник, атакующий молниеносно. Охотится в сумерках и ночью, сопротивляется резкими рывками."
  },
  {
    id: 39,
    zoneId: 7,
    name: "Осётр (стерлядь)",
    role: "bottom",
    rarity: "Rare",
    weightMin: 3.5,
    weightMax: 16.0,
    power: 44,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Вечер",
    preferredBaitId: 2,
    altBaitId: 11,
    minGearTier: 8,
    tierPowerCap: 45,
    sellPrice: 584,
    xp: 143,
    sprite: "fish_039.png",
    emoji: "🐊",
    description: "Донная рыба, обитающая в глубоких местах. Клюёт как зацеп, активна вечером, сопротивляется мощно."
  },
  {
    id: 40,
    zoneId: 7,
    name: "Сом речной",
    role: "bottom",
    rarity: "Uncommon",
    weightMin: 4.0,
    weightMax: 18.0,
    power: 44,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Ночь",
    preferredBaitId: 11,
    altBaitId: 8,
    minGearTier: 8,
    tierPowerCap: 45,
    sellPrice: 468,
    xp: 114,
    sprite: "fish_040.png",
    emoji: "🐈",
    description: "Крупный речной сом, клюющий как зацеп за дно. Ночной охотник, сопротивляется огромной силой."
  },
  {
    id: 41,
    zoneId: 7,
    name: "Лобан",
    role: "peace",
    rarity: "Uncommon",
    weightMin: 1.5,
    weightMax: 4.5,
    power: 39,
    biteStyle: "Тык-тык (мелкие касания)",
    timeOfDay: "День",
    preferredBaitId: 9,
    altBaitId: 1,
    minGearTier: 7,
    tierPowerCap: 40,
    sellPrice: 127,
    xp: 32,
    sprite: "fish_041.png",
    emoji: "🐟",
    description: "Крупная прибрежная рыба, клюющая осторожными касаниями. Держится стаями, активна в дневное время."
  },
  {
    id: 42,
    zoneId: 7,
    name: "Белуга (молодь)",
    role: "bottom",
    rarity: "Uncommon",
    weightMin: 12.0,
    weightMax: 35.0,
    power: 46,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Ночь",
    preferredBaitId: 11,
    altBaitId: 2,
    minGearTier: 9,
    tierPowerCap: 50,
    sellPrice: 2147,
    xp: 525,
    sprite: "fish_042.png",
    emoji: "🐋",
    description: "Молодая белуга, гигантская донная рыба. Атакует мощным рывком, охотится ночью, сопротивляется с огромной силой."
  },
  {
    id: 43,
    zoneId: 8,
    name: "Снаппер красный",
    role: "pred",
    rarity: "Common",
    weightMin: 1.0,
    weightMax: 5.0,
    power: 42,
    biteStyle: "Серия ударов (дробь)",
    timeOfDay: "День",
    preferredBaitId: 9,
    altBaitId: 10,
    minGearTier: 8,
    tierPowerCap: 45,
    sellPrice: 95,
    xp: 23,
    sprite: "fish_043.png",
    emoji: "🐟",
    description: "Морской хищник, атакующий добычу серией ударов. Обитает в прибрежных водах, охотится днём."
  },
  {
    id: 44,
    zoneId: 8,
    name: "Барракуда",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 2.5,
    weightMax: 12.0,
    power: 46,
    biteStyle: "Резкий уход в сторону",
    timeOfDay: "День",
    preferredBaitId: 11,
    altBaitId: 7,
    minGearTier: 9,
    tierPowerCap: 50,
    sellPrice: 308,
    xp: 76,
    sprite: "fish_044.png",
    emoji: "🦈",
    description: "Быстрый морской хищник, атакующий резкими боковыми рывками. Охотится в дневное время, сопротивляется мощно."
  },
  {
    id: 45,
    zoneId: 8,
    name: "Тарпон",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 4.0,
    weightMax: 18.0,
    power: 48,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Вечер",
    preferredBaitId: 9,
    altBaitId: 10,
    minGearTier: 9,
    tierPowerCap: 50,
    sellPrice: 468,
    xp: 114,
    sprite: "fish_045.png",
    emoji: "🐟",
    description: "Крупная морская рыба, атакующая мощным рывком. Наиболее активна вечером, сопротивляется с большой силой."
  },
  {
    id: 46,
    zoneId: 8,
    name: "Групер",
    role: "bottom",
    rarity: "Rare",
    weightMin: 5.5,
    weightMax: 25.0,
    power: 49,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Ночь",
    preferredBaitId: 10,
    altBaitId: 11,
    minGearTier: 9,
    tierPowerCap: 50,
    sellPrice: 913,
    xp: 223,
    sprite: "fish_046.png",
    emoji: "🐠",
    description: "Донный морской хищник, клюющий как зацеп. Обитает в глубоких местах, охотится ночью."
  },
  {
    id: 47,
    zoneId: 8,
    name: "Скат-хвостокол",
    role: "bottom",
    rarity: "Uncommon",
    weightMin: 10.0,
    weightMax: 35.0,
    power: 50,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Ночь",
    preferredBaitId: 11,
    altBaitId: 10,
    minGearTier: 9,
    tierPowerCap: 50,
    sellPrice: 2055,
    xp: 503,
    sprite: "fish_047.png",
    emoji: "🦈",
    description: "Крупный донный скат, клюющий как зацеп. Ночной охотник, сопротивляется огромной силой и весом."
  },
  {
    id: 48,
    zoneId: 8,
    name: "Каранкс",
    role: "pred",
    rarity: "Rare",
    weightMin: 6.0,
    weightMax: 22.0,
    power: 49,
    biteStyle: "Трофейный рывок",
    timeOfDay: "День",
    preferredBaitId: 10,
    altBaitId: 9,
    minGearTier: 9,
    tierPowerCap: 50,
    sellPrice: 838,
    xp: 205,
    sprite: "fish_048.png",
    emoji: "🐟",
    description: "Крупный морской хищник, атакующий мощным рывком. Охотится днём, сопротивляется с большой силой."
  },
  {
    id: 49,
    zoneId: 9,
    name: "Рыба-попугай",
    role: "peace",
    rarity: "Common",
    weightMin: 0.7,
    weightMax: 2.8,
    power: 44,
    biteStyle: "Тык-тык (мелкие касания)",
    timeOfDay: "День",
    preferredBaitId: 9,
    altBaitId: 1,
    minGearTier: 9,
    tierPowerCap: 50,
    sellPrice: 55,
    xp: 13,
    sprite: "fish_049.png",
    emoji: "🦜",
    description: "Яркая рифовая рыба, клюющая осторожными касаниями. Обитает среди кораллов, активна в дневное время."
  },
  {
    id: 50,
    zoneId: 9,
    name: "Спинорог",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 1.2,
    weightMax: 5.5,
    power: 46,
    biteStyle: "Серия ударов (дробь)",
    timeOfDay: "День",
    preferredBaitId: 9,
    altBaitId: 10,
    minGearTier: 9,
    tierPowerCap: 50,
    sellPrice: 143,
    xp: 35,
    sprite: "fish_050.png",
    emoji: "🐡",
    description: "Рифовый хищник, атакующий добычу серией ударов. Обитает среди кораллов, охотится днём."
  },
  {
    id: 51,
    zoneId: 9,
    name: "Крылатка",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 0.6,
    weightMax: 2.2,
    power: 45,
    biteStyle: "Фальстарт (взял/бросил)",
    timeOfDay: "Вечер",
    preferredBaitId: 9,
    altBaitId: 10,
    minGearTier: 9,
    tierPowerCap: 50,
    sellPrice: 60,
    xp: 15,
    sprite: "fish_051.png",
    emoji: "🦁",
    description: "Ядовитый рифовый хищник, осторожно пробующий наживку. Охотится в сумерках среди кораллов."
  },
  {
    id: 52,
    zoneId: 9,
    name: "Рифовый групер",
    role: "bottom",
    rarity: "Rare",
    weightMin: 8.0,
    weightMax: 30.0,
    power: 52,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Ночь",
    preferredBaitId: 10,
    altBaitId: 11,
    minGearTier: 10,
    tierPowerCap: 55,
    sellPrice: 1137,
    xp: 278,
    sprite: "fish_052.png",
    emoji: "🐠",
    description: "Крупный рифовый групер, клюющий как зацеп. Обитает в глубоких местах рифа, охотится ночью."
  },
  {
    id: 53,
    zoneId: 9,
    name: "Гигантский тревалли",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 18.0,
    weightMax: 60.0,
    power: 55,
    biteStyle: "Трофейный рывок",
    timeOfDay: "День",
    preferredBaitId: 10,
    altBaitId: 11,
    minGearTier: 10,
    tierPowerCap: 55,
    sellPrice: 3563,
    xp: 871,
    sprite: "fish_053.png",
    emoji: "🦈",
    description: "Гигантский морской хищник, атакующий мощным рывком. Охотится днём, сопротивляется с огромной силой."
  },
  {
    id: 54,
    zoneId: 9,
    name: "Рифовая акула",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 20.0,
    weightMax: 75.0,
    power: 56,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Ночь",
    preferredBaitId: 11,
    altBaitId: 14,
    minGearTier: 11,
    tierPowerCap: 60,
    sellPrice: 4339,
    xp: 1061,
    sprite: "fish_054.png",
    emoji: "🦈",
    description: "Рифовая акула, атакующая мощным рывком. Ночной охотник, сопротивляется с большой силой."
  },
  {
    id: 55,
    zoneId: 10,
    name: "Сибас",
    role: "pred",
    rarity: "Common",
    weightMin: 0.9,
    weightMax: 4.5,
    power: 48,
    biteStyle: "Серия ударов (дробь)",
    timeOfDay: "Вечер",
    preferredBaitId: 9,
    altBaitId: 10,
    minGearTier: 10,
    tierPowerCap: 55,
    sellPrice: 85,
    xp: 21,
    sprite: "fish_055.png",
    emoji: "🐟",
    description: "Прибрежный хищник, атакующий добычу серией ударов. Охотится в сумерках, активен у берега."
  },
  {
    id: 56,
    zoneId: 10,
    name: "Дорада",
    role: "peace",
    rarity: "Uncommon",
    weightMin: 1.0,
    weightMax: 5.5,
    power: 49,
    biteStyle: "Плавное притапливание",
    timeOfDay: "День",
    preferredBaitId: 9,
    altBaitId: 10,
    minGearTier: 10,
    tierPowerCap: 55,
    sellPrice: 138,
    xp: 34,
    sprite: "fish_056.png",
    emoji: "🐠",
    description: "Прибрежная мирная рыба, клюющая плавно. Обитает у берега, активна в дневное время."
  },
  {
    id: 57,
    zoneId: 10,
    name: "Барабулька",
    role: "peace",
    rarity: "Common",
    weightMin: 0.3,
    weightMax: 1.2,
    power: 46,
    biteStyle: "Тык-тык (мелкие касания)",
    timeOfDay: "День",
    preferredBaitId: 9,
    altBaitId: 2,
    minGearTier: 10,
    tierPowerCap: 55,
    sellPrice: 24,
    xp: 6,
    sprite: "fish_057.png",
    emoji: "🐟",
    description: "Мелкая прибрежная рыба, клюющая осторожными касаниями. Держится у дна, активна днём."
  },
  {
    id: 58,
    zoneId: 10,
    name: "Амберджек",
    role: "pred",
    rarity: "Rare",
    weightMin: 6.0,
    weightMax: 25.0,
    power: 55,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Вечер",
    preferredBaitId: 10,
    altBaitId: 11,
    minGearTier: 10,
    tierPowerCap: 55,
    sellPrice: 928,
    xp: 227,
    sprite: "fish_058.png",
    emoji: "🐟",
    description: "Крупный морской хищник, атакующий мощным рывком. Охотится вечером, сопротивляется с большой силой."
  },
  {
    id: 59,
    zoneId: 10,
    name: "Ставрида",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 0.4,
    weightMax: 1.5,
    power: 47,
    biteStyle: "Серия ударов (дробь)",
    timeOfDay: "День",
    preferredBaitId: 9,
    altBaitId: 10,
    minGearTier: 10,
    tierPowerCap: 55,
    sellPrice: 41,
    xp: 10,
    sprite: "fish_059.png",
    emoji: "🐠",
    description: "Стайная морская рыба, атакующая серией ударов. Держится в толще воды, активна днём."
  },
  {
    id: 60,
    zoneId: 10,
    name: "Кальмар (трофей)",
    role: "pelagic",
    rarity: "Uncommon",
    weightMin: 2.0,
    weightMax: 8.0,
    power: 52,
    biteStyle: "Молниеносная атака",
    timeOfDay: "Ночь",
    preferredBaitId: 10,
    altBaitId: 9,
    minGearTier: 10,
    tierPowerCap: 55,
    sellPrice: 456,
    xp: 112,
    sprite: "fish_060.png",
    emoji: "🦑",
    description: "Крупный кальмар, атакующий молниеносно. Ночной охотник, сопротивляется резкими рывками."
  }
);

// Рыбы 61-90
FISH_DATABASE.push(
  {
    id: 61,
    zoneId: 11,
    name: "Дорадо (махи-махи)",
    role: "pelagic",
    rarity: "Uncommon",
    weightMin: 4.0,
    weightMax: 18.0,
    power: 56,
    biteStyle: "Трофейный рывок",
    timeOfDay: "День",
    preferredBaitId: 10,
    altBaitId: 13,
    minGearTier: 11,
    tierPowerCap: 60,
    sellPrice: 468,
    xp: 114,
    sprite: "fish_061.png",
    emoji: "🐬",
    description: "Пелагический хищник, атакующий мощным рывком. Охотится в открытом море днём, сопротивляется с большой силой."
  },
  {
    id: 62,
    zoneId: 11,
    name: "Королевская скумбрия",
    role: "pelagic",
    rarity: "Uncommon",
    weightMin: 5.0,
    weightMax: 20.0,
    power: 55,
    biteStyle: "Серия ударов (дробь)",
    timeOfDay: "День",
    preferredBaitId: 10,
    altBaitId: 13,
    minGearTier: 11,
    tierPowerCap: 60,
    sellPrice: 531,
    xp: 130,
    sprite: "fish_062.png",
    emoji: "🐟",
    description: "Пелагическая хищная рыба, атакующая серией ударов. Держится в толще воды, охотится днём."
  },
  {
    id: 63,
    zoneId: 11,
    name: "Ваху",
    role: "pelagic",
    rarity: "Rare",
    weightMin: 8.0,
    weightMax: 35.0,
    power: 59,
    biteStyle: "Молниеносная атака",
    timeOfDay: "День",
    preferredBaitId: 13,
    altBaitId: 10,
    minGearTier: 11,
    tierPowerCap: 60,
    sellPrice: 1287,
    xp: 314,
    sprite: "fish_063.png",
    emoji: "🐟",
    description: "Быстрый пелагический хищник, атакующий молниеносно. Охотится в открытом море днём, сопротивляется мощно."
  },
  {
    id: 64,
    zoneId: 11,
    name: "Парусник",
    role: "pelagic",
    rarity: "Uncommon",
    weightMin: 20.0,
    weightMax: 70.0,
    power: 62,
    biteStyle: "Трофейный рывок",
    timeOfDay: "День",
    preferredBaitId: 13,
    altBaitId: 10,
    minGearTier: 12,
    tierPowerCap: 65,
    sellPrice: 4110,
    xp: 1005,
    sprite: "fish_064.png",
    emoji: "⛵",
    description: "Гигантская пелагическая рыба с парусным плавником. Атакует мощным рывком, охотится днём, сопротивляется с огромной силой."
  },
  {
    id: 65,
    zoneId: 11,
    name: "Тунец чернопёрый",
    role: "pelagic",
    rarity: "Rare",
    weightMin: 10.0,
    weightMax: 40.0,
    power: 60,
    biteStyle: "Трофейный рывок",
    timeOfDay: "День",
    preferredBaitId: 10,
    altBaitId: 13,
    minGearTier: 11,
    tierPowerCap: 60,
    sellPrice: 2138,
    xp: 522,
    sprite: "fish_065.png",
    emoji: "🐟",
    description: "Крупный пелагический тунец, атакующий мощным рывком. Охотится в открытом море днём, сопротивляется с большой силой."
  },
  {
    id: 66,
    zoneId: 11,
    name: "Барракуда крупная",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 12.0,
    weightMax: 45.0,
    power: 61,
    biteStyle: "Резкий уход в сторону",
    timeOfDay: "Вечер",
    preferredBaitId: 11,
    altBaitId: 13,
    minGearTier: 12,
    tierPowerCap: 65,
    sellPrice: 2603,
    xp: 636,
    sprite: "fish_066.png",
    emoji: "🦈",
    description: "Крупная барракуда, атакующая резкими боковыми рывками. Охотится вечером, сопротивляется мощно."
  },
  {
    id: 67,
    zoneId: 12,
    name: "Сом канальный",
    role: "bottom",
    rarity: "Common",
    weightMin: 1.8,
    weightMax: 8.5,
    power: 58,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Ночь",
    preferredBaitId: 2,
    altBaitId: 11,
    minGearTier: 11,
    tierPowerCap: 60,
    sellPrice: 162,
    xp: 40,
    sprite: "fish_067.png",
    emoji: "🐈",
    description: "Донный сом, клюющий как зацеп. Ночной охотник, обитает в глубоких местах."
  },
  {
    id: 68,
    zoneId: 12,
    name: "Змееголов",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 2.5,
    weightMax: 12.0,
    power: 61,
    biteStyle: "Резкий уход в сторону",
    timeOfDay: "День",
    preferredBaitId: 8,
    altBaitId: 7,
    minGearTier: 12,
    tierPowerCap: 65,
    sellPrice: 308,
    xp: 76,
    sprite: "fish_068.png",
    emoji: "🐍",
    description: "Агрессивный хищник, атакующий резкими боковыми рывками. Обитает в заросших водоёмах, охотится днём."
  },
  {
    id: 69,
    zoneId: 12,
    name: "Павлиний окунь",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 1.5,
    weightMax: 9.0,
    power: 60,
    biteStyle: "Серия ударов (дробь)",
    timeOfDay: "День",
    preferredBaitId: 7,
    altBaitId: 11,
    minGearTier: 11,
    tierPowerCap: 60,
    sellPrice: 223,
    xp: 55,
    sprite: "fish_069.png",
    emoji: "🦚",
    description: "Яркий хищник, атакующий добычу серией ударов. Обитает в тропических водах, охотится днём."
  },
  {
    id: 70,
    zoneId: 12,
    name: "Аллигатор-гар",
    role: "pred",
    rarity: "Rare",
    weightMin: 10.0,
    weightMax: 55.0,
    power: 66,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Вечер/Ночь",
    preferredBaitId: 8,
    altBaitId: 11,
    minGearTier: 13,
    tierPowerCap: 70,
    sellPrice: 1945,
    xp: 475,
    sprite: "fish_070.png",
    emoji: "🐊",
    description: "Гигантский панцирный хищник, атакующий мощным рывком. Охотится вечером и ночью, сопротивляется с огромной силой."
  },
  {
    id: 71,
    zoneId: 12,
    name: "Сом плоскоголовый",
    role: "bottom",
    rarity: "Uncommon",
    weightMin: 8.0,
    weightMax: 35.0,
    power: 64,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Ночь",
    preferredBaitId: 11,
    altBaitId: 8,
    minGearTier: 12,
    tierPowerCap: 65,
    sellPrice: 1964,
    xp: 480,
    sprite: "fish_071.png",
    emoji: "🐈",
    description: "Крупный донный сом, клюющий как зацеп. Ночной охотник, сопротивляется огромной силой."
  },
  {
    id: 72,
    zoneId: 12,
    name: "Черепаха (ивент-улов)",
    role: "bottom",
    rarity: "Rare",
    weightMin: 3.0,
    weightMax: 8.0,
    power: 61,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "День",
    preferredBaitId: 11,
    altBaitId: 2,
    minGearTier: 12,
    tierPowerCap: 65,
    sellPrice: 329,
    xp: 81,
    sprite: "fish_072.png",
    emoji: "🐢",
    description: "Редкий улов, клюющий как зацеп за дно. Обитает в тропических водах, активна в дневное время."
  },
  {
    id: 73,
    zoneId: 13,
    name: "Пиранья",
    role: "pred",
    rarity: "Common",
    weightMin: 0.7,
    weightMax: 2.5,
    power: 59,
    biteStyle: "Серия ударов (дробь)",
    timeOfDay: "День",
    preferredBaitId: 11,
    altBaitId: 2,
    minGearTier: 12,
    tierPowerCap: 65,
    sellPrice: 50,
    xp: 13,
    sprite: "fish_073.png",
    emoji: "🦷",
    description: "Агрессивная стайная рыба, атакующая серией ударов. Обитает в реках, охотится днём."
  },
  {
    id: 74,
    zoneId: 13,
    name: "Паку",
    role: "peace",
    rarity: "Uncommon",
    weightMin: 3.0,
    weightMax: 18.0,
    power: 62,
    biteStyle: "Плавное притапливание",
    timeOfDay: "День",
    preferredBaitId: 3,
    altBaitId: 4,
    minGearTier: 12,
    tierPowerCap: 65,
    sellPrice: 447,
    xp: 109,
    sprite: "fish_074.png",
    emoji: "🐠",
    description: "Крупная мирная рыба, клюющая плавно. Обитает в тропических реках, активна в дневное время."
  },
  {
    id: 75,
    zoneId: 13,
    name: "Тукунаре",
    role: "pred",
    rarity: "Rare",
    weightMin: 2.5,
    weightMax: 14.0,
    power: 63,
    biteStyle: "Молниеносная атака",
    timeOfDay: "День",
    preferredBaitId: 7,
    altBaitId: 11,
    minGearTier: 12,
    tierPowerCap: 65,
    sellPrice: 494,
    xp: 120,
    sprite: "fish_075.png",
    emoji: "🐟",
    description: "Быстрый тропический хищник, атакующий молниеносно. Охотится днём, сопротивляется резкими рывками."
  },
  {
    id: 76,
    zoneId: 13,
    name: "Сом пираиба",
    role: "bottom",
    rarity: "Uncommon",
    weightMin: 25.0,
    weightMax: 100.0,
    power: 70,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Ночь",
    preferredBaitId: 11,
    altBaitId: 13,
    minGearTier: 13,
    tierPowerCap: 70,
    sellPrice: 5709,
    xp: 1396,
    sprite: "fish_076.png",
    emoji: "🐈",
    description: "Гигантский речной сом, клюющий как зацеп. Ночной охотник, сопротивляется с огромной силой."
  },
  {
    id: 77,
    zoneId: 13,
    name: "Арапайма",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 30.0,
    weightMax: 130.0,
    power: 71,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Вечер",
    preferredBaitId: 11,
    altBaitId: 13,
    minGearTier: 14,
    tierPowerCap: 75,
    sellPrice: 7308,
    xp: 1786,
    sprite: "fish_077.png",
    emoji: "🐉",
    description: "Гигантская древняя рыба, атакующая мощным рывком. Охотится вечером, сопротивляется с огромной силой."
  },
  {
    id: 78,
    zoneId: 13,
    name: "Электрический угорь",
    role: "bottom",
    rarity: "Rare",
    weightMin: 5.0,
    weightMax: 18.0,
    power: 65,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Ночь",
    preferredBaitId: 11,
    altBaitId: 2,
    minGearTier: 12,
    tierPowerCap: 65,
    sellPrice: 688,
    xp: 168,
    sprite: "fish_078.png",
    emoji: "⚡",
    description: "Донный хищник, способный генерировать электрические разряды. Клюёт как зацеп, охотится ночью."
  },
  {
    id: 79,
    zoneId: 14,
    name: "Тиляпия",
    role: "peace",
    rarity: "Common",
    weightMin: 0.7,
    weightMax: 4.0,
    power: 63,
    biteStyle: "Тык-тык (мелкие касания)",
    timeOfDay: "День",
    preferredBaitId: 3,
    altBaitId: 4,
    minGearTier: 12,
    tierPowerCap: 65,
    sellPrice: 74,
    xp: 18,
    sprite: "fish_079.png",
    emoji: "🐟",
    description: "Мирная тропическая рыба, клюющая осторожными касаниями. Обитает в тёплых водах, активна днём."
  },
  {
    id: 80,
    zoneId: 14,
    name: "Африканский сом",
    role: "bottom",
    rarity: "Uncommon",
    weightMin: 5.0,
    weightMax: 25.0,
    power: 67,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Ночь",
    preferredBaitId: 2,
    altBaitId: 11,
    minGearTier: 13,
    tierPowerCap: 70,
    sellPrice: 638,
    xp: 156,
    sprite: "fish_080.png",
    emoji: "🐈",
    description: "Крупный донный сом, клюющий как зацеп. Ночной охотник африканских рек, сопротивляется мощно."
  },
  {
    id: 81,
    zoneId: 14,
    name: "Тигровая рыба",
    role: "pred",
    rarity: "Rare",
    weightMin: 4.0,
    weightMax: 18.0,
    power: 68,
    biteStyle: "Молниеносная атака",
    timeOfDay: "День",
    preferredBaitId: 7,
    altBaitId: 11,
    minGearTier: 13,
    tierPowerCap: 70,
    sellPrice: 658,
    xp: 161,
    sprite: "fish_081.png",
    emoji: "🐯",
    description: "Агрессивный хищник с острыми зубами, атакующий молниеносно. Охотится днём, сопротивляется резкими рывками."
  },
  {
    id: 82,
    zoneId: 14,
    name: "Нильский окунь",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 25.0,
    weightMax: 120.0,
    power: 75,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Вечер",
    preferredBaitId: 11,
    altBaitId: 13,
    minGearTier: 14,
    tierPowerCap: 75,
    sellPrice: 6623,
    xp: 1619,
    sprite: "fish_082.png",
    emoji: "🦈",
    description: "Гигантский хищник африканских озёр, атакующий мощным рывком. Охотится вечером, сопротивляется с огромной силой."
  },
  {
    id: 83,
    zoneId: 14,
    name: "Протоптер",
    role: "bottom",
    rarity: "Uncommon",
    weightMin: 2.5,
    weightMax: 12.0,
    power: 66,
    biteStyle: "Фальстарт (взял/бросил)",
    timeOfDay: "Ночь",
    preferredBaitId: 2,
    altBaitId: 11,
    minGearTier: 13,
    tierPowerCap: 70,
    sellPrice: 308,
    xp: 76,
    sprite: "fish_083.png",
    emoji: "🐟",
    description: "Донная рыба, способная дышать воздухом. Осторожно пробует наживку, охотится ночью."
  },
  {
    id: 84,
    zoneId: 14,
    name: "Сом трофейный",
    role: "bottom",
    rarity: "Rare",
    weightMin: 12.0,
    weightMax: 45.0,
    power: 71,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Ночь",
    preferredBaitId: 11,
    altBaitId: 8,
    minGearTier: 14,
    tierPowerCap: 75,
    sellPrice: 1706,
    xp: 417,
    sprite: "fish_084.png",
    emoji: "🐈",
    description: "Трофейный донный сом, клюющий как зацеп. Ночной охотник, сопротивляется огромной силой."
  },
  {
    id: 85,
    zoneId: 15,
    name: "Мормирус",
    role: "peace",
    rarity: "Common",
    weightMin: 0.8,
    weightMax: 3.0,
    power: 66,
    biteStyle: "Тык-тык (мелкие касания)",
    timeOfDay: "Ночь",
    preferredBaitId: 2,
    altBaitId: 5,
    minGearTier: 13,
    tierPowerCap: 70,
    sellPrice: 60,
    xp: 15,
    sprite: "fish_085.png",
    emoji: "🐟",
    description: "Мирная ночная рыба, клюющая осторожными касаниями. Обитает в африканских реках, активна ночью."
  },
  {
    id: 86,
    zoneId: 15,
    name: "Барбель (афр. сом)",
    role: "bottom",
    rarity: "Uncommon",
    weightMin: 3.5,
    weightMax: 18.0,
    power: 70,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Вечер",
    preferredBaitId: 2,
    altBaitId: 11,
    minGearTier: 13,
    tierPowerCap: 70,
    sellPrice: 457,
    xp: 112,
    sprite: "fish_086.png",
    emoji: "🐈",
    description: "Донная рыба африканских рек, клюющая как зацеп. Охотится вечером, сопротивляется мощно."
  },
  {
    id: 87,
    zoneId: 15,
    name: "Нильский барракудовый",
    role: "pred",
    rarity: "Rare",
    weightMin: 5.0,
    weightMax: 22.0,
    power: 71,
    biteStyle: "Молниеносная атака",
    timeOfDay: "День",
    preferredBaitId: 7,
    altBaitId: 11,
    minGearTier: 14,
    tierPowerCap: 75,
    sellPrice: 808,
    xp: 197,
    sprite: "fish_087.png",
    emoji: "🦈",
    description: "Быстрый речной хищник, атакующий молниеносно. Охотится днём, сопротивляется резкими рывками."
  },
  {
    id: 88,
    zoneId: 15,
    name: "Голиаф-тигр",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 10.0,
    weightMax: 45.0,
    power: 76,
    biteStyle: "Трофейный рывок",
    timeOfDay: "День",
    preferredBaitId: 7,
    altBaitId: 11,
    minGearTier: 15,
    tierPowerCap: 80,
    sellPrice: 2512,
    xp: 614,
    sprite: "fish_088.png",
    emoji: "🐯",
    description: "Легендарный хищник с огромными зубами, атакующий мощным рывком. Охотится днём, сопротивляется с огромной силой."
  },
  {
    id: 89,
    zoneId: 15,
    name: "Вунду (сом)",
    role: "bottom",
    rarity: "Uncommon",
    weightMin: 18.0,
    weightMax: 90.0,
    power: 78,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Ночь",
    preferredBaitId: 11,
    altBaitId: 13,
    minGearTier: 15,
    tierPowerCap: 80,
    sellPrice: 4933,
    xp: 1206,
    sprite: "fish_089.png",
    emoji: "🐈",
    description: "Гигантский донный сом, клюющий как зацеп. Ночной охотник, сопротивляется с огромной силой."
  },
  {
    id: 90,
    zoneId: 15,
    name: "Голиаф-тигр (трофей)",
    role: "pred",
    rarity: "Legendary",
    weightMin: 25.0,
    weightMax: 70.0,
    power: 80,
    biteStyle: "Трофейный рывок",
    timeOfDay: "День",
    preferredBaitId: 11,
    altBaitId: 13,
    minGearTier: 15,
    tierPowerCap: 80,
    sellPrice: 7182,
    xp: 1756,
    sprite: "fish_090.png",
    emoji: "🐯",
    description: "Трофейный голиаф-тигр, атакующий мощным рывком. Охотится днём, сопротивляется с легендарной силой."
  }
);

// Рыбы 91-120
FISH_DATABASE.push(
  {
    id: 91,
    zoneId: 16,
    name: "Скумбрия японская",
    role: "pelagic",
    rarity: "Common",
    weightMin: 0.7,
    weightMax: 3.5,
    power: 70,
    biteStyle: "Серия ударов (дробь)",
    timeOfDay: "День",
    preferredBaitId: 10,
    altBaitId: 9,
    minGearTier: 13,
    tierPowerCap: 70,
    sellPrice: 66,
    xp: 16,
    sprite: "fish_091.png",
    emoji: "🐟",
    description: "Пелагическая стайная рыба, атакующая серией ударов. Держится в толще воды, охотится днём."
  },
  {
    id: 92,
    zoneId: 16,
    name: "Кальмар японский",
    role: "pelagic",
    rarity: "Uncommon",
    weightMin: 1.5,
    weightMax: 6.5,
    power: 72,
    biteStyle: "Молниеносная атака",
    timeOfDay: "Ночь",
    preferredBaitId: 10,
    altBaitId: 9,
    minGearTier: 14,
    tierPowerCap: 75,
    sellPrice: 170,
    xp: 41,
    sprite: "fish_092.png",
    emoji: "🦑",
    description: "Крупный кальмар, атакующий молниеносно. Ночной охотник, сопротивляется резкими рывками."
  },
  {
    id: 93,
    zoneId: 16,
    name: "Хамачи (желтохвост)",
    role: "pelagic",
    rarity: "Uncommon",
    weightMin: 5.0,
    weightMax: 25.0,
    power: 75,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Вечер",
    preferredBaitId: 10,
    altBaitId: 13,
    minGearTier: 14,
    tierPowerCap: 75,
    sellPrice: 638,
    xp: 156,
    sprite: "fish_093.png",
    emoji: "🐟",
    description: "Пелагический хищник, атакующий мощным рывком. Охотится вечером, сопротивляется с большой силой."
  },
  {
    id: 94,
    zoneId: 16,
    name: "Амберджек крупный",
    role: "pelagic",
    rarity: "Rare",
    weightMin: 12.0,
    weightMax: 55.0,
    power: 79,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Вечер",
    preferredBaitId: 13,
    altBaitId: 10,
    minGearTier: 15,
    tierPowerCap: 80,
    sellPrice: 2005,
    xp: 490,
    sprite: "fish_094.png",
    emoji: "🐟",
    description: "Крупный пелагический хищник, атакующий мощным рывком. Охотится вечером, сопротивляется с большой силой."
  },
  {
    id: 95,
    zoneId: 16,
    name: "Тунец (молодь)",
    role: "pelagic",
    rarity: "Rare",
    weightMin: 7.0,
    weightMax: 30.0,
    power: 77,
    biteStyle: "Трофейный рывок",
    timeOfDay: "День",
    preferredBaitId: 13,
    altBaitId: 10,
    minGearTier: 15,
    tierPowerCap: 80,
    sellPrice: 1107,
    xp: 271,
    sprite: "fish_095.png",
    emoji: "🐟",
    description: "Молодой тунец, атакующий мощным рывком. Охотится в открытом море днём, сопротивляется с большой силой."
  },
  {
    id: 96,
    zoneId: 16,
    name: "Жёлтохвост (трофей)",
    role: "pelagic",
    rarity: "Uncommon",
    weightMin: 18.0,
    weightMax: 75.0,
    power: 81,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Вечер",
    preferredBaitId: 13,
    altBaitId: 10,
    minGearTier: 16,
    tierPowerCap: 85,
    sellPrice: 4248,
    xp: 1038,
    sprite: "fish_096.png",
    emoji: "🐟",
    description: "Трофейный жёлтохвост, атакующий мощным рывком. Охотится вечером, сопротивляется с огромной силой."
  },
  {
    id: 97,
    zoneId: 17,
    name: "Сайда",
    role: "pelagic",
    rarity: "Common",
    weightMin: 3.0,
    weightMax: 15.0,
    power: 75,
    biteStyle: "Серия ударов (дробь)",
    timeOfDay: "День",
    preferredBaitId: 10,
    altBaitId: 13,
    minGearTier: 14,
    tierPowerCap: 75,
    sellPrice: 284,
    xp: 69,
    sprite: "fish_097.png",
    emoji: "🐟",
    description: "Пелагическая стайная рыба, атакующая серией ударов. Держится в холодных водах, охотится днём."
  },
  {
    id: 98,
    zoneId: 17,
    name: "Треска",
    role: "bottom",
    rarity: "Uncommon",
    weightMin: 6.0,
    weightMax: 25.0,
    power: 77,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "День",
    preferredBaitId: 12,
    altBaitId: 10,
    minGearTier: 15,
    tierPowerCap: 80,
    sellPrice: 659,
    xp: 161,
    sprite: "fish_098.png",
    emoji: "🐟",
    description: "Донная рыба холодных морей, клюющая как зацеп. Обитает в глубоких местах, активна днём."
  },
  {
    id: 99,
    zoneId: 17,
    name: "Зубатка",
    role: "bottom",
    rarity: "Rare",
    weightMin: 8.0,
    weightMax: 32.0,
    power: 79,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "День",
    preferredBaitId: 12,
    altBaitId: 11,
    minGearTier: 15,
    tierPowerCap: 80,
    sellPrice: 1197,
    xp: 293,
    sprite: "fish_099.png",
    emoji: "🦷",
    description: "Донный хищник с мощными зубами, клюющий как зацеп. Обитает в холодных водах, активен днём."
  },
  {
    id: 100,
    zoneId: 17,
    name: "Палтус",
    role: "bottom",
    rarity: "Uncommon",
    weightMin: 25.0,
    weightMax: 120.0,
    power: 86,
    biteStyle: "Трофейный рывок",
    timeOfDay: "День",
    preferredBaitId: 12,
    altBaitId: 14,
    minGearTier: 17,
    tierPowerCap: 90,
    sellPrice: 6623,
    xp: 1619,
    sprite: "fish_100.png",
    emoji: "🐟",
    description: "Гигантская донная рыба, атакующая мощным рывком. Обитает в глубоких холодных водах, сопротивляется с огромной силой."
  },
  {
    id: 101,
    zoneId: 17,
    name: "Морской чёрт",
    role: "bottom",
    rarity: "Uncommon",
    weightMin: 18.0,
    weightMax: 70.0,
    power: 84,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Ночь",
    preferredBaitId: 14,
    altBaitId: 11,
    minGearTier: 16,
    tierPowerCap: 85,
    sellPrice: 4019,
    xp: 983,
    sprite: "fish_101.png",
    emoji: "👹",
    description: "Глубоководный хищник с устрашающим видом, клюющий как зацеп. Ночной охотник, обитает на больших глубинах."
  },
  {
    id: 102,
    zoneId: 17,
    name: "Треска (трофей)",
    role: "bottom",
    rarity: "Rare",
    weightMin: 18.0,
    weightMax: 45.0,
    power: 81,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "День",
    preferredBaitId: 12,
    altBaitId: 10,
    minGearTier: 16,
    tierPowerCap: 85,
    sellPrice: 1885,
    xp: 461,
    sprite: "fish_102.png",
    emoji: "🐟",
    description: "Трофейная треска, клюющая как зацеп. Обитает в глубоких холодных водах, активна днём."
  },
  {
    id: 103,
    zoneId: 18,
    name: "Тунец желтопёрый",
    role: "pelagic",
    rarity: "Uncommon",
    weightMin: 18.0,
    weightMax: 90.0,
    power: 87,
    biteStyle: "Трофейный рывок",
    timeOfDay: "День",
    preferredBaitId: 13,
    altBaitId: 10,
    minGearTier: 17,
    tierPowerCap: 90,
    sellPrice: 4933,
    xp: 1206,
    sprite: "fish_103.png",
    emoji: "🐟",
    description: "Крупный пелагический тунец, атакующий мощным рывком. Охотится в открытом море днём, сопротивляется с огромной силой."
  },
  {
    id: 104,
    zoneId: 18,
    name: "Марлин синий",
    role: "pelagic",
    rarity: "Legendary",
    weightMin: 60.0,
    weightMax: 200.0,
    power: 92,
    biteStyle: "Трофейный рывок",
    timeOfDay: "День",
    preferredBaitId: 10,
    altBaitId: 13,
    minGearTier: 18,
    tierPowerCap: 95,
    sellPrice: 30996,
    xp: 7577,
    sprite: "fish_104.png",
    emoji: "🗡️",
    description: "Легендарный марлин, атакующий мощным рывком. Охотится в открытом океане днём, сопротивляется с легендарной силой."
  },
  {
    id: 105,
    zoneId: 18,
    name: "Дорадо крупная",
    role: "pelagic",
    rarity: "Rare",
    weightMin: 10.0,
    weightMax: 40.0,
    power: 83,
    biteStyle: "Молниеносная атака",
    timeOfDay: "День",
    preferredBaitId: 13,
    altBaitId: 10,
    minGearTier: 16,
    tierPowerCap: 85,
    sellPrice: 1497,
    xp: 365,
    sprite: "fish_105.png",
    emoji: "🐬",
    description: "Крупная пелагическая рыба, атакующая молниеносно. Охотится в открытом море днём, сопротивляется мощно."
  },
  {
    id: 106,
    zoneId: 18,
    name: "Акула голубая",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 30.0,
    weightMax: 140.0,
    power: 90,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Ночь",
    preferredBaitId: 11,
    altBaitId: 14,
    minGearTier: 17,
    tierPowerCap: 90,
    sellPrice: 8679,
    xp: 2121,
    sprite: "fish_106.png",
    emoji: "🦈",
    description: "Океаническая акула, атакующая мощным рывком. Ночной охотник, сопротивляется с огромной силой."
  },
  {
    id: 107,
    zoneId: 18,
    name: "Парусник океанический",
    role: "pelagic",
    rarity: "Uncommon",
    weightMin: 25.0,
    weightMax: 120.0,
    power: 91,
    biteStyle: "Трофейный рывок",
    timeOfDay: "День",
    preferredBaitId: 13,
    altBaitId: 10,
    minGearTier: 18,
    tierPowerCap: 95,
    sellPrice: 6623,
    xp: 1619,
    sprite: "fish_107.png",
    emoji: "⛵",
    description: "Океанический парусник, атакующий мощным рывком. Охотится в открытом море днём, сопротивляется с огромной силой."
  },
  {
    id: 108,
    zoneId: 18,
    name: "Летучая рыба (редк.)",
    role: "pelagic",
    rarity: "Uncommon",
    weightMin: 0.8,
    weightMax: 3.0,
    power: 76,
    biteStyle: "Фальстарт (взял/бросил)",
    timeOfDay: "День",
    preferredBaitId: 9,
    altBaitId: 10,
    minGearTier: 15,
    tierPowerCap: 80,
    sellPrice: 81,
    xp: 20,
    sprite: "fish_108.png",
    emoji: "🐟",
    description: "Редкая пелагическая рыба, способная выпрыгивать из воды. Осторожно пробует наживку, активна днём."
  },
  {
    id: 109,
    zoneId: 19,
    name: "Рыба-ремень",
    role: "bottom",
    rarity: "Rare",
    weightMin: 8.0,
    weightMax: 30.0,
    power: 84,
    biteStyle: "Фальстарт (взял/бросил)",
    timeOfDay: "Ночь",
    preferredBaitId: 10,
    altBaitId: 14,
    minGearTier: 16,
    tierPowerCap: 85,
    sellPrice: 1137,
    xp: 278,
    sprite: "fish_109.png",
    emoji: "🎀",
    description: "Глубоководная рыба с лентовидным телом, осторожно пробующая наживку. Ночной охотник, обитает на больших глубинах."
  },
  {
    id: 110,
    zoneId: 19,
    name: "Гигантский групер",
    role: "bottom",
    rarity: "Uncommon",
    weightMin: 35.0,
    weightMax: 160.0,
    power: 93,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Ночь",
    preferredBaitId: 11,
    altBaitId: 10,
    minGearTier: 18,
    tierPowerCap: 95,
    sellPrice: 9820,
    xp: 2400,
    sprite: "fish_110.png",
    emoji: "🐠",
    description: "Гигантский донный групер, клюющий как зацеп. Ночной охотник глубоких вод, сопротивляется с огромной силой."
  },
  {
    id: 111,
    zoneId: 19,
    name: "Тунец синепёрый",
    role: "pelagic",
    rarity: "Legendary",
    weightMin: 80.0,
    weightMax: 220.0,
    power: 95,
    biteStyle: "Трофейный рывок",
    timeOfDay: "День",
    preferredBaitId: 13,
    altBaitId: 10,
    minGearTier: 18,
    tierPowerCap: 95,
    sellPrice: 40068,
    xp: 9794,
    sprite: "fish_111.png",
    emoji: "🐟",
    description: "Легендарный синепёрый тунец, атакующий мощным рывком. Охотится в открытом океане днём, сопротивляется с легендарной силой."
  },
  {
    id: 112,
    zoneId: 19,
    name: "Акула-молот",
    role: "pred",
    rarity: "Legendary",
    weightMin: 90.0,
    weightMax: 220.0,
    power: 95,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Ночь",
    preferredBaitId: 14,
    altBaitId: 11,
    minGearTier: 18,
    tierPowerCap: 95,
    sellPrice: 40824,
    xp: 9979,
    sprite: "fish_112.png",
    emoji: "🔨",
    description: "Легендарная акула-молот, атакующая мощным рывком. Ночной охотник, сопротивляется с легендарной силой."
  },
  {
    id: 113,
    zoneId: 19,
    name: "Акула-мако",
    role: "pred",
    rarity: "Legendary",
    weightMin: 70.0,
    weightMax: 200.0,
    power: 95,
    biteStyle: "Трофейный рывок",
    timeOfDay: "День",
    preferredBaitId: 14,
    altBaitId: 11,
    minGearTier: 18,
    tierPowerCap: 95,
    sellPrice: 27972,
    xp: 6838,
    sprite: "fish_113.png",
    emoji: "🦈",
    description: "Легендарная акула-мако, самая быстрая акула. Атакует мощным рывком, охотится днём, сопротивляется с легендарной силой."
  },
  {
    id: 114,
    zoneId: 19,
    name: "Меч-рыба",
    role: "pelagic",
    rarity: "Legendary",
    weightMin: 50.0,
    weightMax: 200.0,
    power: 95,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Ночь",
    preferredBaitId: 14,
    altBaitId: 10,
    minGearTier: 18,
    tierPowerCap: 95,
    sellPrice: 22680,
    xp: 5544,
    sprite: "fish_114.png",
    emoji: "🗡️",
    description: "Легендарная меч-рыба, атакующая мощным рывком. Ночной охотник открытого океана, сопротивляется с легендарной силой."
  },
  {
    id: 115,
    zoneId: 20,
    name: "Бычья акула",
    role: "pred",
    rarity: "Uncommon",
    weightMin: 60.0,
    weightMax: 200.0,
    power: 95,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Вечер",
    preferredBaitId: 11,
    altBaitId: 14,
    minGearTier: 18,
    tierPowerCap: 95,
    sellPrice: 16443,
    xp: 4019,
    sprite: "fish_115.png",
    emoji: "🦈",
    description: "Крупная океаническая акула, атакующая мощным рывком. Охотится вечером, сопротивляется с огромной силой."
  },
  {
    id: 116,
    zoneId: 20,
    name: "Акула тигровая",
    role: "pred",
    rarity: "Legendary",
    weightMin: 120.0,
    weightMax: 220.0,
    power: 95,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Ночь",
    preferredBaitId: 14,
    altBaitId: 11,
    minGearTier: 18,
    tierPowerCap: 95,
    sellPrice: 61992,
    xp: 15154,
    sprite: "fish_116.png",
    emoji: "🐯",
    description: "Легендарная тигровая акула, атакующая мощным рывком. Ночной охотник, сопротивляется с легендарной силой."
  },
  {
    id: 117,
    zoneId: 20,
    name: "Акула белая",
    role: "pred",
    rarity: "Legendary",
    weightMin: 180.0,
    weightMax: 220.0,
    power: 95,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Ночь",
    preferredBaitId: 14,
    altBaitId: 11,
    minGearTier: 18,
    tierPowerCap: 95,
    sellPrice: 81648,
    xp: 19958,
    sprite: "fish_117.png",
    emoji: "🦈",
    description: "Легендарная белая акула, величайший хищник океана. Атакует мощным рывком, охотится ночью, сопротивляется с легендарной силой."
  },
  {
    id: 118,
    zoneId: 20,
    name: "Акула-молот (альфа)",
    role: "pred",
    rarity: "Legendary",
    weightMin: 140.0,
    weightMax: 220.0,
    power: 95,
    biteStyle: "Трофейный рывок",
    timeOfDay: "Ночь",
    preferredBaitId: 14,
    altBaitId: 11,
    minGearTier: 18,
    tierPowerCap: 95,
    sellPrice: 59724,
    xp: 14599,
    sprite: "fish_118.png",
    emoji: "🔨",
    description: "Альфа-самец акулы-молота, атакующий мощным рывком. Ночной охотник, сопротивляется с легендарной силой."
  },
  {
    id: 119,
    zoneId: 20,
    name: "Акула-гренландская",
    role: "pred",
    rarity: "Legendary",
    weightMin: 200.0,
    weightMax: 220.0,
    power: 95,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "Ночь",
    preferredBaitId: 14,
    altBaitId: 11,
    minGearTier: 18,
    tierPowerCap: 95,
    sellPrice: 90720,
    xp: 22176,
    sprite: "fish_119.png",
    emoji: "🦈",
    description: "Легендарная гренландская акула, обитающая в глубоких холодных водах. Клюёт как зацеп, охотится ночью, сопротивляется с легендарной силой."
  },
  {
    id: 120,
    zoneId: 20,
    name: "Китовая акула (ивент)",
    role: "pred",
    rarity: "Legendary",
    weightMin: 200.0,
    weightMax: 220.0,
    power: 95,
    biteStyle: "Донная тяжесть (как зацеп)",
    timeOfDay: "День",
    preferredBaitId: 11,
    altBaitId: 14,
    minGearTier: 18,
    tierPowerCap: 95,
    sellPrice: 136080,
    xp: 33264,
    sprite: "fish_120.png",
    emoji: "🐋",
    description: "Легендарная китовая акула, крупнейшая рыба в мире. Клюёт как зацеп, активна днём, сопротивляется с легендарной силой."
  }
);

// Экспорт для использования в других модулях
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { FISH_DATABASE };
}

// Вспомогательные функции для работы с базой данных рыб
const FishDB = {
  // Получить рыбу по ID
  getById: (id) => FISH_DATABASE.find(fish => fish.id === id),
  
  // Получить всех рыб из зоны
  getByZone: (zoneId) => FISH_DATABASE.filter(fish => fish.zoneId === zoneId),
  
  // Получить рыб по редкости
  getByRarity: (rarity) => FISH_DATABASE.filter(fish => fish.rarity === rarity),
  
  // Получить рыб по роли
  getByRole: (role) => FISH_DATABASE.filter(fish => fish.role === role),
  
  // Получить рыб доступных для текущего уровня снастей
  getByGearTier: (tier) => FISH_DATABASE.filter(fish => fish.minGearTier <= tier),
  
  // Получить случайную рыбу из зоны
  getRandomFromZone: (zoneId) => {
    const zoneFish = FishDB.getByZone(zoneId);
    return zoneFish[Math.floor(Math.random() * zoneFish.length)];
  },
  
  // Получить общее количество рыб
  getTotalCount: () => FISH_DATABASE.length,
  
  // Получить локализованное название (поддерживает fish, monster, junk)
  getLocalizedName: (entry) => {
    if (!entry) return '';
    if (!window.localizationSystem) return entry.name;
    
    // Определяем тип по полю type или по структуре данных
    const type = entry.type || (entry.category ? 'junk' : 'fish');
    
    if (type === 'monster') {
      return window.localizationSystem.getMonsterName(entry.id, entry.name);
    } else if (type === 'junk') {
      return window.localizationSystem.getJunkName(entry.id, entry.name);
    } else {
      return window.localizationSystem.getFishName(entry.id, entry.name);
    }
  },
  
  // Получить локализованное описание (поддерживает fish, monster, junk)
  getLocalizedDescription: (entry) => {
    if (!entry) return '';
    if (!window.localizationSystem) return entry.description;
    
    // Определяем тип по полю type или по структуре данных
    const type = entry.type || (entry.category ? 'junk' : 'fish');
    
    if (type === 'monster') {
      return window.localizationSystem.getMonsterDescription(entry.id, entry.description);
    } else if (type === 'junk') {
      return window.localizationSystem.getJunkDescription(entry.id, entry.description);
    } else {
      return window.localizationSystem.getFishDescription(entry.id, entry.description);
    }
  }
};

// Экспортируем в window для доступа из других модулей
if (typeof window !== 'undefined') {
  window.FISH_DATABASE = FISH_DATABASE;
  window.FishDB = FishDB;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports.FISH_DATABASE = FISH_DATABASE;
  module.exports.FishDB = FishDB;
}


